Run after_save and after_commit even if no changes were made
luckyframework/avram pull request #612
Opened 2021-01-14 20:00 UTC by akadusei

Closes #604

With this, we no longer need #600

2021-01-14 21:48 UTC, matthewmcgarvey approved these changes
I think this is a really good change 👍

2021-01-14 22:16 UTC, jwoertink requested changes
I think this is the best option. Great work on this! Just a few small changes, and we can get this merged in!

2021-01-14 22:16 UTC, jwoertink commented on src/avram/callbacks.cr
> +      to an existing record.
```suggestion
      The after_save and after_commit callbacks are called even if no changes were made
```

2021-01-14 22:16 UTC, jwoertink commented on src/avram/callbacks.cr
> +      to an existing record.
```suggestion
      The after_save and after_commit callbacks are called even if no changes were made
```

2021-01-14 22:16 UTC, jwoertink commented on src/avram/save_operation.cr
> +        insert_or_update if changes.any? || !persisted?
👍

2021-01-14 22:16 UTC, jwoertink commented on src/avram/save_operation.cr
> +  end
This is actually no longer needed. We can just delete it.

2021-01-15 15:56 UTC, jwoertink approved these changes
Awesome! Thank you 🎉

2021-01-15 15:56 UTC, merged