Added custom error message for validate_numeric and validate_size_of …
luckyframework/avram pull request #670
Opened 2021-04-25 11:11 UTC by vishalsodani

…#666

2021-04-28 15:07 UTC, matthewmcgarvey requested changes

2021-04-28 15:07 UTC, matthewmcgarvey commented on src/avram/validations.cr
> +        attribute.add_error message
Can we try to keep the previous messages for both of these validations?

```suggestion
        attribute.add_error message || "is too short"
```

The message param would default to nil

2021-04-29 13:52 UTC, matthewmcgarvey requested changes

2021-04-29 13:52 UTC, matthewmcgarvey commented on src/avram/validations.cr
> +        attribute.add_error message
These still need to have the same changes as you did below, then it will be good 👍

2021-04-29 15:27 UTC, matthewmcgarvey approved these changes
Nice job! 🎉🎉🎉

2021-04-29 15:29 UTC, vishalsodani commented
> Nice job! tadatadatada

Thanks!

2021-04-29 15:32 UTC, matthewmcgarvey commented
@vishalsodani woops, didn't realize that the CI wasn't running. Could you go ahead and tell ameba to ignore those issues? I might try to figure out how to fix them later but it's overkill for this change

Here's docs on how to do it https://github.com/crystal-ameba/ameba#inline-disabling

2021-04-29 15:51 UTC, vishalsodani commented
> @vishalsodani woops, didn't realize that the CI wasn't running. Could you go ahead and tell ameba to ignore those issues? I might try to figure out how to fix them later but it's overkill for this change
> 
> Here's docs on how to do it https://github.com/crystal-ameba/ameba#inline-disabling

I added the ignore comments.

2021-04-29 18:24 UTC, matthewmcgarvey commented
Looks like the disabling didn't get put in the right place. You should be able to check it locally with `bin/ameba` (it's generated with `shards install`)

2021-04-29 19:37 UTC, vishalsodani commented
> Looks like the disabling didn't get put in the right place. You should be able to check it locally with `bin/ameba` (it's generated with `shards install`)

Thanks for the hint. Fixed.

2021-04-30 00:18 UTC, merged